version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false' # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\nMIIDFTCCAf2gAwIBAgIJU4IDEwJbrwjZMA0GCSqGSIb3DQEBCwUAMCgxJjAkBgNV\nBAMTHWxpbmUtY2xvbmUtbG9jYWwuanAuYXV0aDAuY29tMB4XDTIwMTIyODE0NDgz\nNVoXDTM0MDkwNjE0NDgzNVowKDEmMCQGA1UEAxMdbGluZS1jbG9uZS1sb2NhbC5q\ncC5hdXRoMC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC3KdqX\nCHZLQcEPq8Yg5QRj5BM6PsQ4OOPTrT64bUEU0kBwjr9wLTr6KokYaSt+oHVr1D8u\nFN9K+6J0GLgKKTNb+qtA1KXh1Qh5yRqM6DrsxE1nnwIlhyS10RHLJAFELLJenX/G\n2FBLeH63zAnjxmygVYiIqr4uBXb8ALcuzEdXe23MFAEgBFc8QWiowSycUyJZhHtD\n4knbdGhVYPwy5G8FJavtK4Y92guuWN1ZuYJjEJWyEA3xfLP0oTYuaNqePjMzehx2\nkPOV7UFW8EHwsXwfxiWxbygIA54mmA9fw3qkO7vsbOZwKZhQmBhnvybFwCQzVG7U\nc2FbO793EiPb1MjpAgMBAAGjQjBAMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYE\nFBwTJThHaxGu2CshxcIjYvhQQPK6MA4GA1UdDwEB/wQEAwIChDANBgkqhkiG9w0B\nAQsFAAOCAQEAonZFHvxaSM5nJ8A8p6dFg04K01ok3utV7ULetfZQovw2G3cIahZZ\n2IRnh7qQPvK8nEcu5GWwy2FpXOyqHN6c0tFLuK8rphalXFC1U/KH6Oiwkz8R53mv\nDvWfrY7o35mny6EYTl8oxamG/awEAgns/qgpd8a2ILiQKv4VLc9au4IiM8VaslPB\ntNd7obBQ9cqgkCwlwHoRrNL+S4esWlT4GTQ1x/8cXcJZf9U5suOPd5w7MCA83mhD\nSVfYax2szVCCf8V76LBP+xGt8/IucdslELS6meLqoByLN1Dpzxdt1iVAdnokPtpn\ntsZ3SWtn38x5qHTDvT9g0tL5RRdrnnkO6A==\n-----END CERTIFICATE-----"}'
      ## uncomment next line to set an admin secret
volumes:
  db_data:
